language: php
sudo: false

php:
  - '7.2'
  - '7.3'

install:
  - travis_retry composer install --no-interaction

script:
  - bin/phpunit --coverage-text --coverage-clover=coverage.xml tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
