language: php
os: linux
dist: focal

cache:
    directories:
        - $HOME/libsodium

php:
    - '8.0'
    - '8.1'

install:
    - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
    - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
    - php -m | grep -q sodium || (./.travis-ci/travis-install-libsodium.sh && pecl install libsodium)
    - travis_retry composer install --no-interaction

script:
    - bin/phpunit --coverage-text --coverage-clover=coverage.xml tests

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
